### ISSUE TITLE
Deezer Sync Issue

### ISSUE THREAD

**Issue by unxplained** [rnagabhyrava/plex-playlist-sync#26]
Hi,

Getting this error when running the docker container. I am just syncing my deezer playlist
```

INFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync
INFO:root:Missing one or more Spotify Authorization Variables, skipping spotify sync
INFO:root:Spotify playlist sync complete
INFO:root:Starting Deezer playlist sync
Traceback (most recent call last):
  File "/app/./plex-playlist-sync/run.py", line 79, in <module>
    deezer_playlist_sync(dz, plex, userInputs)
  File "/app/plex-playlist-sync/utils/deezer.py", line 105, in deezer_playlist_sync
    playlists = _get_dz_playlists(dz, userInputs)
  File "/app/plex-playlist-sync/utils/deezer.py", line 52, in _get_dz_playlists
    dz_playlists = list(set(dz_user_playlists + dz_id_playlists))
TypeError: unsupported operand type(s) for +: 'PaginatedList' and 'list'
```

**Comment by rnagabhyrava** [comment]
That's weird. Are you using deezer user id to get playlists or pass playlists as ids?

**Comment by rnagabhyrava** [comment]
Fixed in https://github.com/rnagabhyrava/plex-playlist-sync/pull/27

Pull latest image it should be fixed now. I'll leave this open for a couple days for your reply.

**Comment by unxplained** [comment]
Fixed. Appreciate the quick turnaround!
