### ISSUE TITLE
Keep getting error in middle of sync

### ISSUE THREAD

**Issue by vodobaas1** [rnagabhyrava/plex-playlist-sync#61]
**Describe the bug**
A clear and concise description of what the bug is.Traceback (most recent call last):
  File "/app/./plex-playlist-sync/run.py", line 71, in <module>
    spotify_playlist_sync(sp, plex, userInputs)
  File "/app/plex-playlist-sync/utils/spotify.py", line 105, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/app/plex-playlist-sync/utils/plex.py", line 150, in update_or_create_plex_playlist
    available_tracks, missing_tracks = _get_available_plex_tracks(plex, tracks)
  File "/app/plex-playlist-sync/utils/plex.py", line 66, in _get_available_plex_tracks
    search = plex.search(track.title, mediatype="track", limit=5)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 740, in search
    for hub in self.fetchItems(key, Hub):
  File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 267, in fetchItems
    data = self._server.query(ekey, params=url_kw)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 696, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.192', port=32400): Read timed out. (read timeout=30)

**To Reproduce**
1. Configuration:
2. Playlist(s) causing the issue:
3. Song(s) causing the issue:

**Expected behavior**

**Screenshots**
If applicable, add logs to help explain your problem.

**Additional context**

**Comment by rnagabhyrava** [comment]
Looks like plex connection issue. Were you able to access your plex on this machine at that ip address and host?

**Comment by vodobaas1** [comment]
Yes I'm able to connect to my plex via that ip address and I was able to ping my plex server via console.

This is run in the plexplaylistsync console:
PING 192.168.1.192:32400 (192.168.1.192): 56 data bytes
64 bytes from 192.168.1.192: seq=0 ttl=64 time=0.057 ms
64 bytes from 192.168.1.192: seq=1 ttl=64 time=0.058 ms
64 bytes from 192.168.1.192: seq=2 ttl=64 time=0.066 ms

**Comment by rnagabhyrava** [comment]
1. Did it work before and started throwing all of a sudden?
2. If it worked before and just started throwing issues you may try restarting the server/container to see if that fixes the issue.

3. There is an old issue on plex api (which this project uses) about the timeout. It has since been increased to 30 seconds. You may try increasing that to 

https://github.com/pkkid/python-plexapi/issues/57

**Comment by vodobaas1** [comment]
Yes it just started throwing all of a sudden.
I've restarted and it was still throwing the error.
Ah, I will change the timeout and see if that correct it. 

Thanks!

**Comment by vodobaas1** [comment]
So I changed it to 30 seconds and it still times out but not as often it appears.  I will continue to monitor it and see if it persists.  It's odd since I can ping with no problem while it times out.

**Comment by rnagabhyrava** [comment]
I believe that default is now 30 seconds try increasing it to a minute or go crazy and see if that fixes the issue. Mind if I ask you what server you're using? CPU/clock speed.

**Comment by vodobaas1** [comment]
Not at all, I'm using a i7-13700K @ 3400 MHz on Unraid with 64GB RAM.  I'll change it to 60 seconds and see how that works.  Thanks again.

**Comment by vodobaas1** [comment]
So I still haven't been able to change the timeout length.  I've been using PLEXAPI_plexapi_timeout = 60 and it still does 30 seconds.  I'm obviously missing something.  I have been using https://python-plexapi.readthedocs.io/en/latest/configuration.html for refrence.

**Comment by xcrittpm** [comment]
Do you find any solution? I have the same problem...
