### ISSUE TITLE
Sync error, URI too large

### ISSUE THREAD

**Issue by lucidnx** [rnagabhyrava/plex-playlist-sync#66]
Hey! I have recently found that my playlist was empty, so I started digging.
There seems to be size limit, looo at log @bottom.

Sync playlist with 3400 songs.

1. Configuration:
2. Spotify > Plex
3. Playlist(s) causing the issue: Playlist - Spotify

I was not adding any songs to this playlist since first sync, and at that time, it worked. It may be because I have added more songs (files) in Plex that are going to be added by this script.

Container logs:

      
  ```
File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 653, in playlist
    raise NotFound('Unable to find playlist with title "%s".' % title) from None
plexapi.exceptions.NotFound: Unable to find playlist with title "Playlist - Spotify".
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/./plex-playlist-sync/run.py", line 71, in <module>
    spotify_playlist_sync(sp, plex, userInputs)
  File "/app/plex-playlist-sync/utils/spotify.py", line 105, in spotify_playlist_sync
    update_or_create_plex_playlist(plex, playlist, tracks, userInputs)
  File "/app/plex-playlist-sync/utils/plex.py", line 161, in update_or_create_plex_playlist
    plex.createPlaylist(title=playlist.name, items=available_tracks)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 491, in createPlaylist
    return Playlist.create(
  File "/usr/local/lib/python3.10/site-packages/plexapi/playlist.py", line 417, in create
    return cls._create(server, title, items)
  File "/usr/local/lib/python3.10/site-packages/plexapi/playlist.py", line 359, in _create
    data = server.query(key, method=server._session.post)[0]
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 706, in query
    raise BadRequest(message)
plexapi.exceptions.BadRequest: (414) request_uri_too_large; https://plex.domain.co./playlists?smart=0&title=Playlist%20-%20Spotify&type=audio&uri=server%.............%2Fcom.plexapp.plugins.library%2Flibrary%2Fmetadata%2F37222%2C38884%2C..........a lot of content..........166327 <html>
 <head><title>414 Request-URI Too Large</title></head>
 <body>
 <center><h1>414 Request-URI Too Large</h1></center>
```

**Comment by rnagabhyrava** [comment]
Looks like this is an issue on plexapi python package. You can try building the image on your own with updated plexapi package. If it still throwing the error you have to raise an issue there. Sorry I couldn't be of much help on this one. 


https://github.com/pkkid/python-plexapi
